pool:
  vmImage: ubuntu-latest

variables:
- group: NextJsEnvironmentVariablesPPE

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js application'
  env:
    ALGOLIA_APP_ID: $(ALGOLIA_APP_ID)
    ALGOLIA_API_KEY: $(ALGOLIA_API_KEY)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.next'  # Update this path to match your build output
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
