trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: NextJsEnvironmentVariables

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js application'
  env:
    ALGOLIA_APP_ID: $(ALGOLIA_APP_ID)
    ALGOLIA_API_KEY: $(ALGOLIA_API_KEY)
    # Reference other environment variables as needed

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
